FROM node:22-alpine

WORKDIR /app

# Copiar package.json para instalar deps
COPY package*.json ./
RUN npm install

# Copiar el resto
COPY . .

# Exponer el puerto de Vite
EXPOSE 5173

CMD ["npm", "run", "dev"]
